"""petektools — standalone numerics & geostatistics kernels.

A thin Python surface over the Rust ``petektools`` library:

- **sampling** — every ``Sampler`` variant (uniform / normal / lognormal /
  triangular / truncated-normal) plus the ``.clamped()`` combinator, drawn
  through a seeded ``Rng`` for bit-for-bit reproducibility with the Rust engine.
- **stats** — ``mean`` / ``variance`` / ``std`` / ``percentile`` (type-7, Excel
  ``PERCENTILE`` parity) / ``median`` and the weighted family.
- **realization-set helpers** — ``reservoir_summary`` (the P90=low digest) and
  ``aggregate`` (per-segment sum under a correlation assumption).
- **formula** — ``formula_info`` and ``evaluate_formula`` for domain-free
  assignment expressions over named vectors and scalar ``$params``.
- **geostat** — ``experimental_variogram``, ``Variogram`` (fit + params),
  ``local_kriging_grid`` and ``sgs`` over a regular ``Lattice``.
- **interp1d** — 1-D interpolation / log resampling kernels
  (``linear`` / ``nearest`` / ``previous`` / ``next`` / natural ``cubic``).
- **resample** — grid → grid resampling of a native regular grid onto a foreign
  ``Lattice`` (``"bilinear"`` / ``"nearest"``, null- and extent-aware).
- **units** — the SI/metric reporting layer (``m3_to_mcm`` / ``m3_to_msm3`` /
  ``m3_to_bcm`` + inverses, ``scf`` / ``stb`` ↔ ``Sm³``, ``km2`` ↔ ``m2``,
  ``format_volume``).

Vector inputs accept a ``list`` **or** a numpy array (no numpy dependency);
results are plain floats/lists. The P90 = low (petroleum exceedance) convention
is documented on ``reservoir_summary`` / ``ReservoirSummary``.
See https://github.com/kkollsga/petektools.
"""

from ._petektools import (
    AnisotropicVariogram,
    Clamped,
    ExperimentalVariogram,
    Georef,
    Lattice,
    PetroZoneSpec,
    ReservoirSummary,
    Rng,
    Sampler,
    Variogram,
    ZoneSpec,
    __version__,
    aggregate,
    bcm_to_m3,
    closure_outline,
    evaluate_formula,
    experimental_variogram,
    formula_info,
    format_volume,
    interp1d,
    km2_to_m2,
    local_kriging_grid,
    local_kriging_grid_flat,
    m2_to_km2,
    m3_to_bcm,
    m3_to_mcm,
    m3_to_msm3,
    max_dogleg_severity,
    mcm_to_m3,
    mean,
    median,
    msm3_to_m3,
    ntg_curve,
    percentile,
    place_wells,
    place_wells_in_polygon,
    resample,
    resample_flat,
    reservoir_summary,
    scf_to_sm3,
    sgs,
    sgs_flat,
    sm3_to_scf,
    sm3_to_stb,
    std,
    stb_to_sm3,
    study_area_outline,
    synth_dome_surface,
    synth_dome_surface_flat,
    synth_facies_series,
    synth_isochore,
    synth_isochore_flat,
    synth_log_series,
    synth_petro_curves,
    synth_por_with_facies,
    synth_trajectory,
    synth_trajectory_profile,
    synth_trend_map,
    synth_trend_map_flat,
    tops_from_surface,
    variance,
    weighted_mean,
    weighted_percentile,
    weighted_std,
    weighted_variance,
    zone_sample_counts,
)
from .asset import (
    synth_asset,
    write_cps3_grid,
    write_cps3_lines,
    write_earthvision_grid,
    write_irap_grid,
    write_irap_points,
    write_las2,
    write_petrel_tops,
    write_wellpath,
)
from .viewer import (
    WellLabelStyle,
    WellMarkerStyle,
    WellPathStyle,
    WellStyle,
    view2d,
    view2d_payload,
    view3d,
    view3d_payload,
)

__all__ = [
    "Clamped",
    "AnisotropicVariogram",
    "ExperimentalVariogram",
    "Georef",
    "Lattice",
    "PetroZoneSpec",
    "ReservoirSummary",
    "Rng",
    "Sampler",
    "Variogram",
    "WellLabelStyle",
    "WellMarkerStyle",
    "WellPathStyle",
    "WellStyle",
    "ZoneSpec",
    "__version__",
    "aggregate",
    "bcm_to_m3",
    "closure_outline",
    "evaluate_formula",
    "experimental_variogram",
    "formula_info",
    "format_volume",
    "interp1d",
    "km2_to_m2",
    "local_kriging_grid",
    "local_kriging_grid_flat",
    "m2_to_km2",
    "m3_to_bcm",
    "m3_to_mcm",
    "m3_to_msm3",
    "max_dogleg_severity",
    "mcm_to_m3",
    "mean",
    "median",
    "msm3_to_m3",
    "ntg_curve",
    "percentile",
    "place_wells",
    "place_wells_in_polygon",
    "resample",
    "resample_flat",
    "reservoir_summary",
    "scf_to_sm3",
    "sgs",
    "sgs_flat",
    "sm3_to_scf",
    "sm3_to_stb",
    "std",
    "stb_to_sm3",
    "study_area_outline",
    "synth_asset",
    "synth_dome_surface",
    "synth_dome_surface_flat",
    "synth_facies_series",
    "synth_isochore",
    "synth_isochore_flat",
    "synth_log_series",
    "synth_petro_curves",
    "synth_por_with_facies",
    "synth_trajectory",
    "synth_trajectory_profile",
    "synth_trend_map",
    "synth_trend_map_flat",
    "tops_from_surface",
    "variance",
    "view2d",
    "view2d_payload",
    "view3d",
    "view3d_payload",
    "weighted_mean",
    "weighted_percentile",
    "weighted_std",
    "weighted_variance",
    "write_cps3_grid",
    "write_cps3_lines",
    "write_earthvision_grid",
    "write_irap_grid",
    "write_irap_points",
    "write_las2",
    "write_petrel_tops",
    "write_wellpath",
    "zone_sample_counts",
]
